### ISSUE TITLE
Finalize annotations for the signature manifest

### ISSUE THREAD

**Issue by SteveLasker** [notaryproject/specifications#103] opened 2021-10-12 01:01 UTC
We currently have the following to enable filtering on the different signatures:
```json
"annotations": {
  "org.cncf.notary.signature.subject": "wabbit-networks.io"
}
```

This will need more details for how the key is identified for filtering.

**Comment by iamsamirzon** [comment] 2022-07-15 21:21
Closing, as we have defined the annotations for signature manifest here https://github.com/notaryproject/notaryproject/blob/main/signature-specification.md#storage.

Plus the filtering aspect called out here is a duplicate of https://github.com/notaryproject/notation/issues/63

**Closed as completed by iamsamirzon** 2022-07-15 21:21 UTC
Labels: duplicate, spec
